name: Kaggle Test 09-13

on:
  schedule:
    - cron: '0 1 * * *' # 新加坡时间 9:00
  workflow_dispatch:

jobs:
  kaggle-task:
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME_09_13: ${{ secrets.KAGGLE_USERNAME_09_13 }}
      KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN_09_13 }}
      KERNEL_SLUG: ${{ secrets.KERNEL_SLUG }}
      KERNEL_DATASET: ${{ secrets.KERNEL_DATASET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install kaggle
          sudo apt-get install jq -y

      - name: Delete Temp Kernel
        run: |
          kaggle kernels delete "${KAGGLE_USERNAME_09_13}/${KERNEL_SLUG}-temp" -y || echo "Temp kernel not found or already deleted."

      - name: Pull Latest Notebook
        run: |
          kaggle kernels pull -p ./ "$KERNEL_SLUG";
          echo "Successfully pulled: $KERNEL_SLUG"

      - name: Create Kernel Metadata
        run: |
          FETCHED_FILE="${KERNEL_SLUG}.ipynb"
          
          TEMP_ID="${KAGGLE_USERNAME_09_13}/${KERNEL_SLUG}-temp"
          TEMP_TITLE="${KERNEL_SLUG}-temp"
          
          jq -n \
            --arg id "$TEMP_ID" \
            --arg title "$TEMP_TITLE" \
            --arg dataset "$KERNEL_DATASET" \
            --arg code_file "$FETCHED_FILE" \
            '{
              "id": $id,
              "title": $title,
              "code_file": $code_file,
              "language": "python",
              "kernel_type": "notebook",
              "is_private": "true",
              "enable_gpu": "true",
              "enable_tpu": "false",
              "enable_internet": "true",
              "dataset_sources": (if $dataset == "" then [] else [$dataset] end),
              "competition_sources": [],
              "kernel_sources": [],
              "model_sources": []
            }' > kernel-metadata.json
          
          echo "Generated kernel-metadata.json with ID: $TEMP_ID"

      - name: Push and Run Notebook
        run: |
          kaggle kernels push -p ./ -t 15300
          echo "Done."